---
vagrant_hostname: demacvm.dev
vagrant_machine_name: demacvm
vagrant_ip: 192.168.33.10

# Allow VM to be accessed via a public network interface on your host.
# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# windows example for local_path C:\\www\\sites
vagrant_synced_folders:
  - local_path: ~/Sites/www
    destination: /srv/www
    type:
    create: true

  - local_path: ~/Sites/mysql
    destination: /srv/mysql
    type:
    create: true
    owner: 500      # mysql user  not created yet, but will have this id when the box is provisioned
    group: 500      # mysql group not created yet, but will have this id when the box is provisioned

  - local_path: ~/Sites/backup
    destination: /srv/backup
    type:
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 4096
vagrant_cpus: 2

# Optional Software to install
optional_software:
  elasticsearch: false
  solr: false
  rabbitmq: false

# Configure PHP
config_php:
  - version: 5.4.45
    shortname: 5.4
    port: 9004
    build: false
    enabled: true

  - version: 5.5.34
    shortname: 5.5
    port: 9005
    build: false
    enabled: true

  - version: 5.6.20
    shortname: 5.6
    port: 9006
    build: false
    enabled: true

  - version: 7.0.8
    shortname: 7
    port: 9007
    build: false
    enabled: true

  - version: 7.1.12
    shortname: 7.1
    port: 9008
    build: false
    enabled: true

# Configure Users
#  For no home    use '-'
#  For no shell   use '-'
#  For no comment use '-'
config_users:
  - uid: 500
    gid: 500
    name: mysql
    home: '-'
    shell: /bin/false
    comment: 'MySql Server'

  - uid: 501
    gid: 501
    name: redis
    home: /var/lib/redis
    shell: /bin/false
    comment: 'Redis Server'

  - uid: 502
    gid: 502
    name: varnish
    home: /home/varnish
    shell: /bin/false
    comment: 'Varnish Server'

  - uid: 503
    gid: 503
    name: varnishlog
    home: /home/varnishlog
    shell: /bin/false
    comment: 'VarnishLog'

# Configure Groups
config_groups:
  - gid: 500
    name: mysql

  - gid: 501
    name: redis

  - gid: 502
    name: varnish

  - gid: 503
    name: varnishlog